"""add pixel column

Revision ID: 84f08d821245
Revises: 
Create Date: 2025-04-04 16:14:42.428157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f08d821245'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inhibition_zone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pixel', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inhibition_zone', schema=None) as batch_op:
        batch_op.drop_column('pixel')

    # ### end Alembic commands ###
