"""Set cascade delete

Revision ID: bd0413edfc66
Revises: 84f08d821245
Create Date: 2025-04-22 17:55:07.849251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0413edfc66'
down_revision = '84f08d821245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inhibition_zone', schema=None) as batch_op:
        batch_op.drop_constraint('inhibition_zone_test_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'asttest', ['test_id'], ['test_id'], ondelete='CASCADE')

    with op.batch_alter_table('inhibition_zone_history', schema=None) as batch_op:
        batch_op.drop_constraint('inhibition_zone_history_test_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'asttest', ['test_id'], ['test_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inhibition_zone_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inhibition_zone_history_test_id_fkey', 'asttest', ['test_id'], ['test_id'], ondelete='SET NULL')

    with op.batch_alter_table('inhibition_zone', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inhibition_zone_test_id_fkey', 'asttest', ['test_id'], ['test_id'], ondelete='SET NULL')

    # ### end Alembic commands ###
